#!/bin/sh

# Delete all containers
sudo docker rm inmemorydatasingle
sudo docker rm inmemorydatadouble
sudo docker rm inmemorydatatriple
sudo docker rm inmemorydataquadruple
sudo docker rm inmemorybenchmarksingle
sudo docker rm inmemorybenchmarkdouble1
sudo docker rm inmemorybenchmarkdouble2
sudo docker rm inmemorybenchmarktriple1
sudo docker rm inmemorybenchmarktriple2
sudo docker rm inmemorybenchmarktriple3
sudo docker rm inmemorydataquadruple1
sudo docker rm inmemorydataquadruple2
sudo docker rm inmemorydataquadruple3
sudo docker rm inmemorydataquadruple4
sudo docker rm inmemorydata6-1
sudo docker rm inmemorydata6-2
sudo docker rm inmemorydata6-3
sudo docker rm inmemorydata6-4
sudo docker rm inmemorydata6-5
sudo docker rm inmemorydata6-6
sudo docker rm inmemorydata8-1
sudo docker rm inmemorydata8-2
sudo docker rm inmemorydata8-3
sudo docker rm inmemorydata8-4
sudo docker rm inmemorydata8-5
sudo docker rm inmemorydata8-6
sudo docker rm inmemorydata8-7
sudo docker rm inmemorydata8-8
sudo docker rm inmemorydata8
sudo docker rm inmemorydata6
sudo docker rm inmemorydata10-1
sudo docker rm inmemorydata10-2
sudo docker rm inmemorydata10-3
sudo docker rm inmemorydata10-4
sudo docker rm inmemorydata10-5
sudo docker rm inmemorydata10-6
sudo docker rm inmemorydata10-7
sudo docker rm inmemorydata10-8
sudo docker rm inmemorydata10-9
sudo docker rm inmemorydata10-10
sudo docker rm inmemorydata10


# Delete all images
sudo docker rmi cloudsuite/in-memory-analytics
sudo docker rmi cloudsuite/movielens-dataset
