# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'appa-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: 'prometheus_local'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodeexporter_remote'
    scrape_interval: 5s
    static_configs:
      - targets: ['SERVER_PUBLIC_IP_ADDRESS:9100']

  - job_name: 'cadvisor_remote'
    scrape_interval: 5s
    static_configs:
      - targets: ['SERVER_PUBLIC_IP_ADDRESS:8080']

  - job_name: 'pushgateway_remote'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['SERVER_PUBLIC_IP_ADDRESS:9091']

  - job_name: 'docker_remote'
         # metrics_path defaults to '/metrics'
         # scheme defaults to 'http'.
    static_configs:
      - targets: ['SERVER_PUBLIC_IP_ADDRESS:9323']
